services:
  - type: web
    name: bakeryapp-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # You need to set this manually in Render dashboard
      - key: PORT
        fromService:
          type: web
          name: bakeryapp-backend
          property: port
